Repository mdn/kuma, pull requests merged in 2018-05, with the labels that each got.

#4760 bug 1451261: Use twitter icon for Mozilla twitter
  jinja2/includes/footer/moz-footer.html
Labels: frontend

#4769 bug 773921: remove wiki.new_revision_based_on endpoint
  kuma/wiki/jinja2/wiki/revision.html
  kuma/wiki/tests/test_templates.py
  kuma/wiki/tests/test_views.py
  kuma/wiki/urls.py
  kuma/wiki/views/edit.py
  kuma/wiki/views/translate.py
Labels: CDN for developer.mozilla.org

#4765 bug 1431259: add headless tests for cdn
  requirements/constraints.txt
  tests/conftest.py
  tests/headless/test_cdn.py
Labels: CDN for developer.mozilla.org

#4776 fix(a11y): remove aria-hidden from social svg
  jinja2/includes/icons/social/facebook.svg
  jinja2/includes/icons/social/github.svg
  jinja2/includes/icons/social/instagram.svg
  jinja2/includes/icons/social/linkedin.svg
  jinja2/includes/icons/social/stack-overflow.svg
  jinja2/includes/icons/social/twitter.svg
Labels: a11y

#4815 feat(callout): Fix Bug 1462835, replace saucelabs banner with new perception survey
  jinja2/includes/footer/mdn-footer.html
  jinja2/includes/footer/moz-footer.html
  kuma/landing/jinja2/landing/homepage.html
  kuma/settings/common.py
  kuma/static/img/embed/promos/survey.svg
  kuma/static/styles/components/home/column-callout.scss
  kuma/users/jinja2/socialaccount/snippets/login_service_icon.html
Labels: frontend
