Repository mdn/kuma, pull requests merged in 2018-10, with the labels that each got.

#4996 Bug 924583: Use $blue-dark for link color against grey background
  kuma/static/styles/base/elements/typography.scss
  kuma/static/styles/components/tags.scss
Labels: a11y, frontend

#4999 Add lang attributes to language switcher
  kuma/wiki/jinja2/wiki/includes/buttons.html
Labels: frontend

#4969 Change in content icons to svg stage1
  kuma/static/styles/components/wiki/indicators.scss
  kuma/static/styles/font-awesome.scss
  kuma/static/styles/libs/font-awesome/fonts/FontAwesome.otf
  kuma/static/styles/libs/font-awesome/fonts/fontawesome-webfont.eot
  kuma/static/styles/libs/font-awesome/fonts/fontawesome-webfont.otf
  kuma/static/styles/libs/font-awesome/fonts/fontawesome-webfont.svg
  kuma/static/styles/libs/font-awesome/fonts/fontawesome-webfont.ttf
  kuma/static/styles/libs/font-awesome/fonts/fontawesome-webfont.woff
  kuma/static/styles/libs/font-awesome/fonts/fontawesome-webfont.woff2
  kuma/static/styles/libs/font-awesome/scss/_core.scss
  kuma/static/styles/libs/font-awesome/scss/_icons.scss
  kuma/static/styles/libs/font-awesome/scss/_variables.scss
Labels: frontend, performance

#4957 Front-end assets work for removing the MozToggler sidebar behavior
  kuma/static/js/wiki.js
  kuma/static/styles/components/wiki/quick-links.scss
Labels: frontend

#5000 Add accessible text to social icons
  jinja2/includes/icons/social/discourse.svg
  jinja2/includes/icons/social/facebook.svg
  jinja2/includes/icons/social/github.svg
  jinja2/includes/icons/social/instagram.svg
  jinja2/includes/icons/social/linkedin.svg
  jinja2/includes/icons/social/stack-overflow.svg
  jinja2/includes/icons/social/twitter.svg
Labels: a11y, frontend

#5024 Subsetting Zilla Slab
  jinja2/includes/preload.html
  kuma/static/fonts/locales/ZillaSlab-Bold.subset.woff
  kuma/static/fonts/locales/ZillaSlab-Bold.subset.woff2
  kuma/static/fonts/locales/ZillaSlab-Regular.subset.woff
  kuma/static/fonts/locales/ZillaSlab-Regular.subset.woff2
  kuma/static/latin-subset
  kuma/static/styles/locales/_zilla.scss
Labels: frontend, performance

#4954 Fix Bug 1479817, anchor link headings are obscured by toc
  kuma/settings/common.py
  kuma/static/js/components/local-anchor.js
  kuma/static/js/components/page-load-actions.js
  kuma/static/js/utils/utils.js
  kuma/static/js/wiki-toc.js
  kuma/static/styles/base/elements/document.scss
  kuma/static/styles/components/wiki/elements.scss
Labels: frontend

#5038 Bug 1498685, remove smooth scrolling
  kuma/static/styles/base/elements/document.scss
Labels: a11y, frontend

#5023 Fix Bug 1491154, switch from Verdana to Arial
  kuma/static/styles/base/elements/document.scss
  kuma/static/styles/base/elements/forms.scss
  kuma/static/styles/base/elements/typography.scss
  kuma/static/styles/components/contribution/form.scss
  kuma/static/styles/components/home/column-callout.scss
  kuma/static/styles/components/home/home-hacks.scss
  kuma/static/styles/components/home/home-masthead.scss
  kuma/static/styles/components/structure/nav-footer.scss
  kuma/static/styles/components/structure/socialaccount-providers.scss
  kuma/static/styles/components/users/user-links.scss
  kuma/static/styles/components/users/user-tags.scss
  kuma/static/styles/components/wiki/communitybox.scss
  kuma/static/styles/components/wiki/content/card-grid.scss
  kuma/static/styles/components/wiki/content/originaldocinfo.scss
  kuma/static/styles/components/wiki/crumbs.scss
  kuma/static/styles/components/wiki/indicators.scss
  kuma/static/styles/components/wiki/quick-links.scss
  kuma/static/styles/components/wiki/toc.scss
  kuma/static/styles/includes/_mixins.scss
  kuma/static/styles/includes/_mixins_indicators.scss
  kuma/static/styles/includes/_vars.scss
  media/maintenance/css/maintenance.css
Labels: frontend

#5053 Fix Bug 1496826, some icons are missing from the font-awesome bundle
  kuma/static/styles/components/wiki/indicators.scss
  kuma/static/styles/libs/font-awesome/fonts/fontawesome-webfont.eot
  kuma/static/styles/libs/font-awesome/fonts/fontawesome-webfont.otf
  kuma/static/styles/libs/font-awesome/fonts/fontawesome-webfont.svg
  kuma/static/styles/libs/font-awesome/fonts/fontawesome-webfont.ttf
  kuma/static/styles/libs/font-awesome/fonts/fontawesome-webfont.woff
  kuma/static/styles/libs/font-awesome/fonts/fontawesome-webfont.woff2
Labels: frontend
