Repository mdn/kuma, pull requests merged in 2018-07, with the labels that each got.

#4860 Add jinja helper for SVG. Fix issue 23 on sprints repo
  jinja2/includes/footer/mdn-footer.html
  jinja2/includes/footer/moz-footer.html
  kuma/users/jinja2/socialaccount/snippets/login_service_icon.html
  kuma/wiki/templatetags/jinja_helpers.py
  kuma/wiki/tests/test_helpers.py
Labels: a11y

#4878 bug 1418301: Remove preload hints for iframe assets
  kuma/wiki/jinja2/wiki/document.html
Labels: frontend, performance

#4853 Death of zones 1462475
  docs/data.rst
  kuma/landing/views.py
  kuma/redirects/redirects.py
  kuma/scrape/tests/test_source_document_rendered.py
  kuma/settings/common.py
  kuma/static/js/wiki-skinny.js
  kuma/static/js/wiki.js
  kuma/static/styles/archive.scss
  kuma/static/styles/zone-addons.scss
  kuma/static/styles/zone-apps.scss
  kuma/static/styles/zone-archive.scss
  kuma/static/styles/zone-b2g.scss
  kuma/static/styles/zone-connect.scss
  kuma/static/styles/zone-firefox.scss
  kuma/static/styles/zone-games.scss
  kuma/static/styles/zone-learn.scss
  kuma/static/styles/zone-marketplace.scss
  kuma/static/styles/zone-ten.scss
  kuma/static/styles/zones.scss
  kuma/static/styles/zones/base.scss
  kuma/static/styles/zones/components/callout.scss
  kuma/static/styles/zones/components/chapters.scss
  kuma/static/styles/zones/components/dev-program.scss
  kuma/static/styles/zones/components/initial-steps.scss
  kuma/static/styles/zones/components/learnmore.scss
  kuma/static/styles/zones/components/outer-apps-box.scss
  kuma/static/styles/zones/components/parent.scss
  kuma/static/styles/zones/components/promo10.scss
  kuma/static/styles/zones/components/quote.scss
  kuma/static/styles/zones/components/stack-form.scss
  kuma/static/styles/zones/components/subnav.scss
  kuma/static/styles/zones/components/webext-summary-compat-table.scss
  kuma/wiki/admin.py
  kuma/wiki/jinja2/wiki/document.html
  kuma/wiki/jinja2/wiki/includes/buttons.html
  kuma/wiki/jinja2/wiki/includes/document_macros.html
  kuma/wiki/jobs.py
  kuma/wiki/middleware.py
  kuma/wiki/models.py
  kuma/wiki/signal_handlers.py
  kuma/wiki/templatetags/jinja_helpers.py
  kuma/wiki/tests/conftest.py
  kuma/wiki/tests/test_helpers.py
  kuma/wiki/tests/test_jobs.py
  kuma/wiki/tests/test_middleware.py
  kuma/wiki/tests/test_models_document.py
  kuma/wiki/tests/test_templates.py
  kuma/wiki/tests/test_views.py
  kuma/wiki/tests/test_views_document.py
  kuma/wiki/tests/test_views_list.py
  kuma/wiki/tests/test_views_misc.py
  kuma/wiki/urls.py
  kuma/wiki/views/document.py
  tests/headless/map_301.py
  tests/headless/test_cdn.py
  tests/headless/test_redirects.py
  tests/utils/urls.py
Labels: Death of Zones

#4858 bug 1469029: keep two zone-related css classes
  kuma/static/styles/base/utilities.scss
  kuma/static/styles/components/wiki/customcss.scss
Labels: Death of Zones

#4893 Fix Bug 1477263, change event label for RUM data
  kuma/static/js/interactive.js
  kuma/static/js/utils/post-message-handler.js
Labels: frontend

#4881 Inline dnt-helper
  jinja2/base.html
  kuma/settings/common.py
  kuma/static/js/libs/mozilla.dnthelper.min.js
Labels: frontend, performance
