Repository mdn/kuma, pull requests merged in 2018-09, with the labels that each got.

#4967 Bug 1490392: Reduce web font usage
  jinja2/includes/preload.html
  kuma/static/fonts/OpenSans-Bold-webfont.woff
  kuma/static/fonts/OpenSans-Bold-webfont.woff2
  kuma/static/fonts/OpenSans-BoldItalic-webfont.woff
  kuma/static/fonts/OpenSans-BoldItalic-webfont.woff2
  kuma/static/fonts/OpenSans-Italic-webfont.woff
  kuma/static/fonts/OpenSans-Italic-webfont.woff2
  kuma/static/fonts/OpenSans-Light-webfont.woff
  kuma/static/fonts/OpenSans-Light-webfont.woff2
  kuma/static/fonts/OpenSans-LightItalic-webfont.woff
  kuma/static/fonts/OpenSans-LightItalic-webfont.woff2
  kuma/static/fonts/OpenSans-Regular-webfont.woff
  kuma/static/fonts/OpenSans-Regular-webfont.woff2
  kuma/static/fonts/OpenSans-Semibold-webfont.woff
  kuma/static/fonts/OpenSans-Semibold-webfont.woff2
  kuma/static/fonts/OpenSans-SemiboldItalic-webfont.woff
  kuma/static/fonts/OpenSans-SemiboldItalic-webfont.woff2
  kuma/static/fonts/locales/ZillaSlab-BoldItalic.woff
  kuma/static/fonts/locales/ZillaSlab-BoldItalic.woff2
  kuma/static/fonts/locales/ZillaSlab-Italic.woff
  kuma/static/fonts/locales/ZillaSlab-Italic.woff2
  kuma/static/fonts/locales/ZillaSlab-Light.woff
  kuma/static/fonts/locales/ZillaSlab-Light.woff2
  kuma/static/fonts/locales/ZillaSlab-LightItalic.woff
  kuma/static/fonts/locales/ZillaSlab-LightItalic.woff2
  kuma/static/fonts/locales/ZillaSlab-Medium.woff
  kuma/static/fonts/locales/ZillaSlab-Medium.woff2
  kuma/static/fonts/locales/ZillaSlab-MediumItalic.woff
  kuma/static/fonts/locales/ZillaSlab-MediumItalic.woff2
  kuma/static/fonts/locales/ZillaSlab-RegularItalic.woff
  kuma/static/fonts/locales/ZillaSlab-RegularItalic.woff2
  kuma/static/fonts/locales/ZillaSlab-SemiBold.woff
  kuma/static/fonts/locales/ZillaSlab-SemiBold.woff2
  kuma/static/fonts/locales/ZillaSlab-SemiBoldItalic.woff
  kuma/static/fonts/locales/ZillaSlab-SemiBoldItalic.woff2
  kuma/static/styles/base/elements/document.scss
  kuma/static/styles/base/elements/forms.scss
  kuma/static/styles/components/wiki/toc.scss
  kuma/static/styles/gaia.scss
  kuma/static/styles/includes/_mixins.scss
  kuma/static/styles/includes/_vars.scss
  kuma/static/styles/locales/_zilla.scss
  kuma/static/styles/main.scss
  media/gaia/shared/style_unstable/progress_activity/index.html
  media/gaia/shared/style_unstable/seekbars.css
  media/gaia/shared/style_unstable/seekbars/index.html
  media/gaia/shared/style_unstable/tabs.css
  media/gaia/shared/style_unstable/tabs/filters.html
  media/gaia/shared/style_unstable/tabs/index.html
  media/maintenance/css/maintenance.css
Labels: frontend, performance

#4981 Fix alignment of icons and titles in search results
  kuma/static/styles/search.scss
Labels: frontend

#4986 Move section link after heading
  kuma/static/js/components/local-anchor.js
  kuma/static/js/libs/icons.js
  kuma/static/styles/components/wiki/elements.scss
Labels: a11y, frontend

#4998 Add aria-current role to current page
  kuma/wiki/jinja2/wiki/includes/document_macros.html
Labels: a11y, frontend

#4987 Move close button to start of menu
  kuma/static/js/components.js
Labels: a11y, frontend
