Repository mdn/kuma, pull requests merged in 2018-04, with the labels that each got.

#4733 bug 1431259: fix caching for miel endpoint
  kuma/urls.py
Labels: CDN for developer.mozilla.org

#4734 bug 1431259: do not cache docs if logged-in user or ks errors
  kuma/wiki/tests/test_views.py
  kuma/wiki/views/document.py
Labels: CDN for developer.mozilla.org

#4739 Fix Bug 1450646, remove type attribute from script tags
  jinja2/403.html
  jinja2/404.html
  jinja2/429.html
  jinja2/base.html
  jinja2/includes/config.html
  jinja2/includes/google_analytics.html
  kuma/landing/jinja2/landing/promote_buttons.html
  kuma/static/js/libs/ckeditor/build/ckeditor/plugins/wsc/dialogs/ciframe.html
  kuma/static/js/libs/ckeditor/build/ckeditor/plugins/wsc/dialogs/tmpFrameset.html
  kuma/static/js/libs/ckeditor/source/plugins/wsc/dialogs/ciframe.html
  kuma/static/js/libs/ckeditor/source/plugins/wsc/dialogs/tmpFrameset.html
  kuma/users/jinja2/account/email.html
  kuma/users/jinja2/account/password_reset.html
  kuma/users/jinja2/users/user_edit.html
  kuma/wiki/jinja2/403-create-page.html
  kuma/wiki/jinja2/wiki/code_sample.html
  kuma/wiki/jinja2/wiki/document.html
  kuma/wiki/jinja2/wiki/edit.html
  kuma/wiki/jinja2/wiki/includes/tag_suggestions.html
  kuma/wiki/jinja2/wiki/list/revisions.html
  kuma/wiki/tests/test_views_code.py
  media/maintenance/index.html
Labels: cleanup, manual merge

#4740 bug 1431259: remove compression middleware and its tests
  kuma/attachments/tests/test_views.py
  kuma/core/middleware.py
  kuma/core/tests/test_middleware.py
  kuma/settings/common.py
  kuma/wiki/tests/test_views_code.py
  kuma/wiki/tests/test_views_document.py
  requirements/default.txt
Labels: CDN for developer.mozilla.org

#4746 Do not preload fonts set as optional
  jinja2/includes/preload.html
Labels: frontend, performance

#4756 fix: Adds titles to social icons and reoptimise svg
  jinja2/includes/icons/social/facebook.svg
  jinja2/includes/icons/social/github.svg
  jinja2/includes/icons/social/instagram.svg
  jinja2/includes/icons/social/linkedin.svg
  jinja2/includes/icons/social/stack-overflow.svg
  jinja2/includes/icons/social/twitter.svg
  jinja2/includes/icons/web-service/jsfiddle.svg
  kuma/wiki/tests/test_views.py
  package.json
Labels: frontend
