Repository mdn/kuma, pull requests merged in 2018-08, with the labels that each got.

#4902 bug 1445641, bug 1464892: enable deployment recording
  Jenkinsfiles/push.groovy
  Jenkinsfiles/utils.groovy
Labels: record deployments

#4901 Fix Bug 1307217, add link to section elements to improve ux
  kuma/settings/common.py
  kuma/static/img/icons/link.svg
  kuma/static/js/components/local-anchor.js
  kuma/static/styles/components/wiki/elements.scss
  kuma/static/styles/includes/_mixins.scss
Labels: frontend

#4903 Update and optimise images in hero area
  kuma/landing/jinja2/landing/homepage.html
  kuma/static/img/hero-dino.png
  kuma/static/img/home-bg.gif
  kuma/static/img/home-dino.gif
  kuma/static/styles/components/home/home-masthead.scss
Labels: frontend, performance

#4907 Fix Bug 1478442, remove sprite fallback image for callouts
  kuma/static/img/embed/promo-sprite.png
  kuma/static/img/embed/promo-sprite.psd
  kuma/static/styles/components/home/column-callout.scss
Labels: frontend

#4938 Fix Bug 1482538, replace survey banner with fx-dev banner
  kuma/landing/jinja2/landing/homepage.html
  kuma/static/img/embed/promos/fx-dev-background.svg
  kuma/static/img/embed/promos/fx-dev-logo.png
  kuma/static/styles/components/home/column-callout.scss
Labels: frontend

#4912 Fix Bug 1450922, improve homepage layout for hacks and contribute sections
  kuma/landing/jinja2/landing/homepage.html
  kuma/landing/tests/test_views.py
  kuma/landing/views.py
  kuma/settings/common.py
  kuma/static/img/home-globe.jpg
  kuma/static/styles/base/icons.scss
  kuma/static/styles/base/utilities.scss
  kuma/static/styles/components/home/base.scss
  kuma/static/styles/components/home/home-contribute.scss
  kuma/static/styles/components/home/home-hacks.scss
  kuma/wiki/tasks.py
  kuma/wiki/tests/test_tasks.py
Labels: cleanup, frontend, performance

#4946 Fix Bug 1485302, use rel=noopener when using target=_blank
  jinja2/includes/header-main-nav.html
Labels: frontend
