Repository mdn/kuma, pull requests merged in 2019-09, with the labels that each got.

#5701 Issue #5685, remove Emotion and move CSS to Sass - Document and Sidebar
  kuma/javascript/src/document.jsx
  kuma/static/styles/minimalist/document.scss
  kuma/static/styles/minimalist/structure/_containers.scss
  kuma/static/styles/minimalist/structure/_sidebar.scss
Labels: cleanup, frontend, performance

#5706 Issue #5685, remove Emotion and move CSS to Sass - loading bar
  kuma/javascript/src/router.jsx
  kuma/static/styles/minimalist/components/_loading-bar.scss
  kuma/static/styles/minimalist/main.scss
Labels: cleanup, frontend, performance

#5707 Issue #5685, remove Emotion and move CSS to Sass - search results page
  kuma/javascript/src/search-results-page.jsx
  kuma/static/styles/minimalist/structure/_search-results.scss
Labels: cleanup, frontend, performance

#5709 Issue #5685, remove Emotion and move CSS to Sass - titlebar
  kuma/javascript/src/titlebar.jsx
  kuma/static/styles/minimalist/components/_titlebar.scss
  kuma/static/styles/minimalist/document.scss
  kuma/static/styles/minimalist/vars/_vars-color-palette.scss
Labels: cleanup, frontend, performance

#5704 Issue #5685, remove Emotion and move CSS to Sass - Login
  kuma/javascript/src/header/__snapshots__/header.test.js.snap
  kuma/javascript/src/header/__snapshots__/login.test.js.snap
  kuma/javascript/src/header/login.jsx
  kuma/static/styles/minimalist/components/_login.scss
  kuma/static/styles/minimalist/main.scss
Labels: cleanup, frontend, performance

#5708 Issue #5685, remove Emotion and move CSS to Sass - task completion survey
  kuma/javascript/src/task-completion-survey.jsx
  kuma/static/styles/minimalist/components/_task-completion.scss
  kuma/static/styles/minimalist/document.scss
Labels: cleanup, frontend, performance

#5705 Issue #5685, remove Emotion and move CSS to Sass - search widget
  kuma/javascript/src/header/__snapshots__/header.test.js.snap
  kuma/javascript/src/header/__snapshots__/search.test.js.snap
  kuma/javascript/src/header/search.jsx
  kuma/static/styles/minimalist/components/_search-widget.scss
  kuma/static/styles/minimalist/main.scss
Labels: cleanup, frontend, performance

#5710 Fixes #5685, remove Emotion and move CSS to Sass - cleanup
  babel.config.js
  jest.config.js
  kuma/javascript/src/layout.jsx
  kuma/javascript/src/ssr.jsx
  package-lock.json
  package.json
Labels: cleanup, frontend, not ready, performance

#5736 Fixes #5735, remove document editing and management styling from new frontend
  kuma/static/styles/minimalist/document.scss
Labels: cleanup, frontend, performance

#5739 Delete section anchor links
  kuma/javascript/src/article.jsx
  kuma/javascript/src/icons/anchor.svg
  kuma/javascript/src/section-anchor.jsx
Labels: merge when green

#5694 Fixes #5688, remove fancyTOC.scss from new frontend
  kuma/static/styles/minimalist/document.scss
  kuma/static/styles/wiki-shared.scss
Labels: cleanup, frontend, performance

#5698 Fixes #5697, use correct structure partial for new frontend
  kuma/static/styles/minimalist/components/_main-nav.scss
  kuma/static/styles/minimalist/document.scss
Labels: cleanup, frontend, performance

#5747 Fixes #5746, adds hard-source-webpack-plugin
  package-lock.json
  package.json
  webpack-build-utils/presets/webpack.hardsource.js
Labels: tooling

#5775 Fixes #5774, remove newsletter.js from new frontend
  kuma/wiki/jinja2/wiki/react_document.html
Labels: cleanup, frontend

#5691 preload ZillaSlab-Regular
  jinja2/includes/preload.html
Labels: frontend, performance

#5780 diff never again
  .travis.yml
Labels: do not merge

#5839 Fixes #5752, search input field always grey
  kuma/static/styles/minimalist/components/_search-widget.scss
Labels: bug

#5834 Fixes #5828, use react header on new signup flow
  kuma/javascript/src/index.jsx
  kuma/javascript/src/signup-flow.jsx
  kuma/javascript/src/ssr.jsx
  kuma/users/jinja2/socialaccount/signup.html
Labels: frontend, mdn-accounts

#5842 scrape_document with trailing slash fails
  kuma/scrape/management/commands/__init__.py
Labels: PR

#5794 Removes the need to restart SSR after build
  package-lock.json
  package.json
  webpack-build-utils/terminal.js
Labels: tooling

#5843 Fixes #5829, adds new header to updated user signup flow
  jinja2/includes/icons/brand/mdn-auth.svg
  jinja2/includes/icons/general/auth-checkmark.svg
  jinja2/includes/icons/social/github-auth.svg
  kuma/settings/common.py
  kuma/static/styles/minimalist/components/_auth-service-header.scss
  kuma/static/styles/minimalist/structure/signup-flow.scss
  kuma/users/jinja2/socialaccount/signup.html
Labels: frontend

#5866 Fixes #5799, remove communitbox styling
  kuma/static/styles/components/wiki/communitybox.scss
  kuma/static/styles/minimalist/document.scss
  kuma/static/styles/wiki.scss
Labels: frontend

#5863 Fixes #5859, improve accessibility of custom lang dropdown
  kuma/javascript/src/header/__snapshots__/dropdown.test.js.snap
  kuma/javascript/src/header/__snapshots__/language-menu.test.js.snap
  kuma/javascript/src/header/__snapshots__/login.test.js.snap
  kuma/javascript/src/header/dropdown.jsx
  kuma/javascript/src/header/language-menu.jsx
  kuma/static/styles/minimalist/components/_dropdown.scss
Labels: a11y, blocker

#5884 Remove unused settings constants
  kuma/settings/common.py
Labels: type: refactor
