Repository mdn/kuma, pull requests merged in 2019-12, with the labels that each got.

#6012 chore(deps): Update Prism to v1.17
  bower.json
  kuma/static/js/libs/prism/prism-bash.js
  kuma/static/js/libs/prism/prism-core.js
  kuma/static/js/libs/prism/prism-css-extras.js
  kuma/static/js/libs/prism/prism-css.js
  kuma/static/js/libs/prism/prism-javascript.js
  kuma/static/js/libs/prism/prism-json.js
  kuma/static/js/libs/prism/prism-line-highlight.js
  kuma/static/js/libs/prism/prism-rust.js
Labels: p5

#5998 Support serving files from S3 instead of EFS
  docker-compose.yml
  kuma/attachments/migrations/0003_auto_20191016_storage.py
  kuma/attachments/models.py
  kuma/attachments/tests/conftest.py
  kuma/attachments/tests/test_models.py
  kuma/attachments/tests/test_views.py
  kuma/attachments/views.py
  kuma/settings/common.py
  kuma/settings/testing.py
  requirements/default.txt
Labels: comp: backend

#6038 Add Google OAuth as another authentication provider
  docs/installation.rst
  kuma/attachments/management/commands/configure_github_social.py
  kuma/settings/common.py
  kuma/users/fixtures/test_users.json
  kuma/users/jinja2/socialaccount/signup.html
  kuma/users/management/__init__.py
  kuma/users/management/commands/__init__.py
  kuma/users/management/commands/configure_social_auth.py
  kuma/users/providers/google/__init__.py
  kuma/users/providers/google/provider.py
  kuma/users/providers/google/urls.py
  kuma/users/providers/google/views.py
  kuma/users/templatetags/jinja_helpers.py
  kuma/users/tests/test_adapters.py
  kuma/users/views.py
Labels: KR: Membership Accts, p1

#6094 Fixes #6024, add multi auth sign-in ui
  .prettierignore
  jinja2/includes/auth-modal-content.html
  jinja2/includes/auth-modal.html
  jinja2/includes/config.html
  jinja2/includes/icons/auth/github-auth.svg
  jinja2/includes/icons/auth/google-auth.svg
  jinja2/includes/icons/general/checkmark-isolated.svg
  jinja2/includes/icons/general/close-modal.svg
  jinja2/includes/icons/social/github-auth.svg
  jinja2/includes/modal.html
  jinja2/includes/style.html
  jinja2/react_base.html
  kuma/javascript/src/header/__snapshots__/header.test.js.snap
  kuma/javascript/src/header/__snapshots__/login.test.js.snap
  kuma/javascript/src/header/login.jsx
  kuma/settings/common.py
  kuma/static/js/components/modal.js
  kuma/static/js/components/user-signup/auth-modal.js
  kuma/static/styles/minimalist/atoms/_mixins-lists.scss
  kuma/static/styles/minimalist/components/_auth-benefits.scss
  kuma/static/styles/minimalist/components/_auth-providers.scss
  kuma/static/styles/minimalist/components/_card.scss
  kuma/static/styles/minimalist/components/_modal.scss
  kuma/static/styles/minimalist/components/auth-modal.scss
  kuma/static/styles/minimalist/molecules/_buttons.scss
  kuma/static/styles/minimalist/structure/_signup-landing.scss
  kuma/static/styles/minimalist/structure/signup-flow.scss
  kuma/static/styles/minimalist/utils/_utility-mixins.scss
  kuma/static/styles/minimalist/vars/_vars-color-palette.scss
  kuma/static/styles/minimalist/vars/_vars-media-queries.scss
  kuma/users/jinja2/socialaccount/signup-landing.html
  kuma/users/urls.py
  kuma/users/views.py
  kuma/wiki/jinja2/wiki/react_document.html
Labels: KR: Membership Accts
