Repository mdn/kuma, pull requests merged in 2019-10, with the labels that each got.

#5928 Fixes #5927, remove compact.scss from codebase
  kuma/settings/common.py
  kuma/static/styles/components/compact.scss
  kuma/static/styles/main.scss
  kuma/static/styles/minimalist/main.scss
  kuma/wiki/jinja2/wiki/includes/kumascript_errors.html
Labels: 25% refactoring

#5919 Fixes #5892, create header css bundle
  jinja2/includes/style.html
  jinja2/react_base.html
  kuma/settings/common.py
  kuma/static/styles/minimalist/atoms/_logo.scss
  kuma/static/styles/minimalist/base/_structure.scss
  kuma/static/styles/minimalist/components/_dropdown.scss
  kuma/static/styles/minimalist/components/_page-header.scss
  kuma/static/styles/minimalist/main.scss
  kuma/static/styles/minimalist/organisms/header.scss
  kuma/wiki/jinja2/wiki/react_document.html
Labels: cleanup, frontend, type: refactor

#5936 Remove selectivzr from jinja template
  jinja2/base.html
  jinja2/react_base.html
  kuma/settings/common.py
  kuma/static/js/libs/selectivizr/selectivizr.js
Labels: p5

#5598 Full Front End for MDN Signaling on Beta
  kuma/api/v1/serializers.py
  kuma/api/v1/views.py
  kuma/javascript/src/article.jsx
  kuma/javascript/src/bcd-signal.jsx
  kuma/javascript/src/bcd.js
  kuma/settings/common.py
  kuma/static/img/arrow-right-blue.svg
  kuma/static/img/dino-confuse.svg
  kuma/static/img/dino-happy.svg
  kuma/static/img/icn-check.svg
  kuma/static/img/icn-remove.svg
  kuma/static/styles/components/compat-tables/_bc-signal.scss
  kuma/wiki/jinja2/wiki/react_document.html
  kuma/wiki/migrations/0005_auto_20190805_0306.py
  kuma/wiki/models.py
  package.json
  webpack-build-utils/presets/webpack.bcd.js
Labels: type: feature, type: support

#5758 chore(editorconfig): Enforce consistent indentation
  .editorconfig
Labels: meta: missing user story, p5

#6050 use pretty-quick
  package-lock.json
  package.json
Labels: meta: 25% refactoring

#6066 don't depend on window.ga till it's actually needed
  kuma/javascript/src/ga-provider.jsx
  kuma/javascript/src/ga-provider.test.js
Labels: p1

#5872 Issue#5819 add interpolated with elements
  kuma/javascript/src/__snapshots__/l10n.test.jsx.snap
  kuma/javascript/src/l10n.js
  kuma/javascript/src/l10n.test.jsx
  kuma/javascript/src/newsletter.jsx
Labels: meta: do not merge
