Repository mdn/kuma, pull requests merged in 2019-08, with the labels that each got.

#5610 django 1.11.23
  requirements/default.txt
Labels: merge when green

#5611 Bug 1569816, switch highlight section to CSS only
  kuma/javascript/src/article.jsx
  kuma/settings/common.py
  kuma/static/styles/components/home/home-masthead.scss
  kuma/static/styles/components/wiki/content/static/_highlighted-headings.scss
  kuma/static/styles/includes/_mixins.scss
  kuma/static/styles/main-shared.scss
Labels: merge when green

#5620 reinstate zilla font on wiki
  jinja2/base.html
Labels: merge when green

#5638 avoid excess wiki_document get queries on /docs/Web
  kuma/api/v1/views.py
Labels: performance

#5632 Bug 1571137, ensure documents use appropriate landmarks
  jinja2/base.html
  jinja2/react_base.html
  kuma/javascript/src/document.jsx
  kuma/landing/jinja2/landing/react_homepage.html
Labels: a11y

#5659 Fix issue #5645, update copy for new user registration
  kuma/users/jinja2/socialaccount/signup.html
  kuma/users/tests/test_templates.py
Labels: merge when green

#5674 Fixes issue #5668, segment breadcrumb CSS
  kuma/javascript/src/breadcrumbs.jsx
  kuma/javascript/src/document.jsx
  kuma/javascript/src/document.test.js
  kuma/javascript/src/titlebar.jsx
  kuma/static/styles/minimalist/components/_breadcrumbs.scss
  kuma/static/styles/minimalist/document.scss
  kuma/static/styles/minimalist/structure/_containers.scss
Labels: cleanup, frontend, performance

#5677 Fixes issue #5676, load banners CSS conditionally
  kuma/landing/jinja2/landing/react_homepage.html
  kuma/settings/common.py
  kuma/wiki/jinja2/wiki/react_document.html
Labels: frontend, performance

#5679 create print stylesheet and serve with media=print
  jinja2/base.html
  jinja2/react_base.html
  kuma/settings/common.py
  kuma/static/styles/base/elements/sectioning.scss
  kuma/static/styles/base/utilities.scss
  kuma/static/styles/components/components.scss
  kuma/static/styles/components/newsletter.scss
  kuma/static/styles/components/structure/global-notice.scss
  kuma/static/styles/components/structure/nav-footer.scss
  kuma/static/styles/components/wiki/contributors.scss
  kuma/static/styles/components/wiki/crumbs.scss
  kuma/static/styles/components/wiki/edit-section.scss
  kuma/static/styles/components/wiki/edit/page-attachments.scss
  kuma/static/styles/components/wiki/offline-dialog-content.scss
  kuma/static/styles/components/wiki/page-buttons.scss
  kuma/static/styles/components/wiki/sample-code.scss
  kuma/static/styles/components/wiki/structure.scss
  kuma/static/styles/minimalist/document.scss
  kuma/static/styles/minimalist/mixins/_print-mixins.scss
  kuma/static/styles/minimalist/print.scss
  kuma/static/styles/minimalist/structure/_footer.scss
  kuma/static/styles/wiki-shared.scss
  kuma/static/styles/wiki.scss
  kuma/wiki/jinja2/wiki/document.html
  kuma/wiki/jinja2/wiki/react_document.html
Labels: cleanup, frontend

#5702 Issue #5685, remove Emotion and move CSS to Sass - Dropdown
  kuma/javascript/src/header/__snapshots__/dropdown.test.js.snap
  kuma/javascript/src/header/__snapshots__/language-menu.test.js.snap
  kuma/javascript/src/header/__snapshots__/login.test.js.snap
  kuma/javascript/src/header/dropdown.jsx
  kuma/static/styles/minimalist/components/_dropdown.scss
  kuma/static/styles/minimalist/components/_main-nav.scss
  kuma/static/styles/minimalist/document.scss
  kuma/static/styles/minimalist/vars/_vars-nav.scss
Labels: cleanup, frontend, performance

#5725 Fixes #5722, remove beta notice
  kuma/javascript/src/header/__snapshots__/header.test.js.snap
  kuma/javascript/src/header/header.jsx
Labels: cleanup, frontend, performance

#5716 Fixes #5696, remove promos CSS and related assets
  kuma/static/img/embed/promos/sauce-labs-wiki-a-high-res.png
  kuma/static/img/embed/promos/sauce-labs-wiki-a.png
  kuma/static/img/embed/promos/sauce-labs-wiki-b-high-res.png
  kuma/static/img/embed/promos/sauce-labs-wiki-b.png
  kuma/static/img/embed/promos/sauce-labs-wiki-c-high-res.png
  kuma/static/img/embed/promos/sauce-labs-wiki-c.png
  kuma/static/styles/components/wiki/promos.scss
  kuma/static/styles/minimalist/document.scss
  kuma/static/styles/wiki.scss
Labels: cleanup, do not merge, frontend, performance

#5727 Fixes #5726, instrument events on section links
  kuma/static/js/components/local-anchor.js
Labels: frontend
