Repository mdn/kuma, pull requests merged in 2020-03, with the labels that each got.

#6633 Add subscriptions banner
  docs/feature-toggles.rst
  kuma/api/v1/tests/test_views.py
  kuma/banners/jinja2/banners/cta-banners.html
  kuma/core/migrations/0004_create_subscription_banner_flag.py
  kuma/javascript/src/banners.jsx
  kuma/javascript/src/banners.test.js
  kuma/javascript/src/signup-flow.jsx
  kuma/landing/jinja2/landing/homepage.html
  kuma/landing/jinja2/landing/includes/style.html
  kuma/landing/jinja2/landing/react_homepage.html
  kuma/settings/common.py
  kuma/static/styles/components/banners/_common.scss
  kuma/static/styles/components/banners/base.scss
  kuma/static/styles/components/banners/developer-needs.scss
  kuma/static/styles/components/banners/mdn-subscriptions.scss
  kuma/static/styles/minimalist/vars/_vars-color-palette.scss
  kuma/wiki/jinja2/wiki/document.html
  kuma/wiki/jinja2/wiki/includes/banner-styles.html
  kuma/wiki/jinja2/wiki/react_document.html
Labels: meta: do not merge

#5425 bug 1553162 - react_i18n_check
  kuma/core/apps.py
  kuma/core/checks.py
  kuma/core/tests/test_checks.py
  kuma/settings/common.py
Labels: p1

#5417 bug 1551941 - retry on SMTPServerDisconnected
  kuma/core/tests/test_utils.py
  kuma/core/utils.py
  kuma/users/tasks.py
  kuma/wiki/tasks.py
Labels: meta: missing user story, p3, type: bug report
