Repository mdn/kuma, pull requests merged in 2020-04, with the labels that each got.

#6674 Add instructions for adding a React page
  docs/development.rst
Labels: comp: workflow

#6928 Responsive toc
  kuma/javascript/src/icons/caret-down.svg
  kuma/javascript/src/toc.jsx
  kuma/static/styles/components/wiki/_toc.scss
  kuma/static/styles/minimalist/structure/_article.scss
  kuma/static/styles/minimalist/structure/_containers.scss
Labels: merge when green

#6957 codecov submission with retry
  .travis.yml
  scripts/ci-codecovsubmit
Labels: meta: do not merge
