Repository mdn/kuma, pull requests merged in 2020-02, with the labels that each got.

#6407 Update MDN Profile to MDN Account
  kuma/users/jinja2/socialaccount/signup.html
  kuma/users/tests/test_templates.py
Labels: KR: Membership Accts, comp: frontend

#6446 Remove jQueryUI, interest and expertise fields - Profile cleanup
  kuma/scrape/sources/user.py
  kuma/scrape/tests/test_source_user.py
  kuma/scrape/tests/test_storage.py
  kuma/settings/common.py
  kuma/static/js/users.js
  kuma/static/styles/components/users/_user-tags.scss
  kuma/static/styles/users.scss
  kuma/users/forms.py
  kuma/users/jinja2/users/includes/user_title_info.html
  kuma/users/jinja2/users/user_edit.html
  kuma/users/migrations/0015_remove_user_tags.py
  kuma/users/models.py
  kuma/users/tests/test_views.py
  kuma/users/views.py
Labels: KR: Membership Accts

#6604 Remove signup header on signup page and update copy
  kuma/static/styles/minimalist/components/_auth-service-header.scss
  kuma/static/styles/minimalist/structure/signup-flow.scss
  kuma/users/jinja2/socialaccount/signup.html
  kuma/users/tests/test_templates.py
Labels: KR: Membership Accts, comp: frontend

#6594 Upgrade to Django 2.2
  kuma/core/tests/test_views.py
  kuma/core/urlresolvers.py
  kuma/settings/common.py
  kuma/users/migrations/0016_auto_20200226_0353.py
  kuma/users/tests/test_models.py
  kuma/users/tests/test_views.py
  kuma/wiki/tasks.py
  kuma/wiki/templates/admin/wiki/document/load_data_form.html
  kuma/wiki/templates/admin/wiki/purge_documents.html
  kuma/wiki/tests/test_admin.py
  poetry.lock
  pyproject.toml
Labels: meta: do not merge
